-- MySQL Script generated by MySQL Workbench
-- Mon Dec 19 10:53:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jwt-authentication
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jwt-authentication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jwt-authentication` DEFAULT CHARACTER SET utf8 ;
USE `jwt-authentication` ;

-- -----------------------------------------------------
-- Table `jwt-authentication`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jwt-authentication`.`users` ;

CREATE TABLE IF NOT EXISTS `jwt-authentication`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `jwt-authentication`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `jwt-authentication`;
INSERT INTO `jwt-authentication`.`users` (`id`, `username`, `password`) VALUES (1, 'user1', 'user1234');

COMMIT;

